// frontend-vue/src/components/Layout.vue
<template>
  <div class="app-layout">
    <!-- Mobile Overlay -->
    <div v-if="mobileOpen" class="fixed inset-0 bg-black/50 z-40" @click="mobileOpen = false"></div>

    <!-- SIDEBAR -->
    <aside :class="['sidebar', { open: mobileOpen }]">
      <!-- Header -->
      <div class="sidebar-header">
        <div class="sidebar-logo">
          <AppLogo :size="42" />
          <div class="sidebar-logo-text">
            <h2>SIMZAKAT</h2>
            <p>UPZ KEMENAG KEBUMEN</p>
          </div>
        </div>

        <div class="sidebar-user">
          <div style="display: flex; align-items: center; justify-content: space-between;">
            <div>
              <div class="user-name">{{ user?.name || 'Administrator' }}</div>
              <div class="user-email">{{ user?.email || 'admin@kemenag.go.id' }}</div>
            </div>
            <span class="badge badge-green" style="font-size: 10px;">{{ user?.role || 'Admin' }}</span>
          </div>
        </div>
      </div>

      <!-- Nav Items -->
      <nav class="sidebar-nav">
        <div v-for="group in navGroups" :key="group.label">
          <div class="nav-section-label">{{ group.label }}</div>
          <div
            v-for="item in group.items"
            :key="item.key"
            :class="['nav-item', { active: activeTab === item.key }]"
            @click="navigate(item.key)"
          >
            <component :is="item.icon" :size="17" style="flex-shrink: 0;" />
            <span style="flex: 1;">{{ item.label }}</span>
            <ChevronRight v-if="activeTab === item.key" :size="14" style="opacity: 0.7;" />
          </div>
        </div>
      </nav>

      <!-- Footer -->
      <div class="sidebar-footer">
        <button class="btn-logout" @click="logout">
          <LogOut :size="16" /> Keluar (Logout)
        </button>
      </div>
    </aside>

    <!-- MAIN CONTENT -->
    <div class="main-content">
      <header class="topbar">
        <div style="display: flex; align-items: center; gap: 10px;">
          <div>
            <div class="topbar-title">{{ pageTitle }}</div>
            <div class="topbar-breadcrumb">SIMZAKAT » {{ pageTitle }}</div>
          </div>
        </div>
        <div class="topbar-badges">
          <span class="badge badge-blue">
            <UserCheck :size="13" style="margin-right: 4px;" /> Hak Akses: {{ user?.role || 'Admin' }}
          </span>
          <span class="badge badge-green">
            <CheckCircle :size="13" style="margin-right: 4px;" /> Sistem Aktif (PSAK 109)
          </span>
        </div>
      </header>

      <main class="page-content">
        <slot></slot>
      </main>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import AppLogo from './AppLogo.vue';
import {
  LayoutDashboard,
  Users,
  HeartHandshake,
  Target,
  FolderKanban,
  ClipboardCheck,
  ArrowDownLeft,
  ArrowUpRight,
  TrendingDown,
  BookOpen,
  FileSpreadsheet,
  RefreshCw,
  Scale,
  BarChart3,
  TrendingUp,
  FileText,
  Landmark,
  Archive,
  Calculator,
  Database,
  History,
  ShieldCheck,
  Settings as SettingsIcon,
  LogOut,
  CheckCircle,
  ChevronRight,
  UserCheck,
} from '@lucide/vue';

const props = defineProps<{
  activeTab: string;
  user: any;
}>();

const emit = defineEmits<{
  (e: 'navigate', tab: string): void;
  (e: 'logout'): void;
}>();

const mobileOpen = ref(false);

const navGroups = [
  {
    label: 'MENU UTAMA',
    items: [
      { key: 'dashboard', label: 'Ikhtisar Dashboard', icon: LayoutDashboard },
    ],
  },
  {
    label: 'DATA MASTER',
    items: [
      { key: 'muzakki', label: 'Data Muzakki', icon: Users },
      { key: 'mustahik', label: 'Data Mustahik', icon: HeartHandshake },
    ],
  },
  {
    label: 'PERENCANAAN',
    items: [
      { key: 'collection-plans', label: 'Rencana Penghimpunan', icon: Target },
      { key: 'programs', label: 'Program Penyaluran', icon: FolderKanban },
      { key: 'program-control', label: 'Kontrol Program', icon: ClipboardCheck },
    ],
  },
  {
    label: 'TRANSAKSI',
    items: [
      { key: 'penerimaan', label: 'Penerimaan Dana', icon: ArrowDownLeft },
      { key: 'penyaluran', label: 'Penyaluran Dana', icon: ArrowUpRight },
      { key: 'operasional', label: 'Pengeluaran Operasional', icon: TrendingDown },
    ],
  },
  {
    label: 'PEMBUKUAN',
    items: [
      { key: 'chart-of-accounts', label: 'Chart of Accounts', icon: BookOpen },
      { key: 'buku-kas', label: 'Buku Kas Umum', icon: FileSpreadsheet },
      { key: 'mutasi-kas-bank', label: 'Mutasi Kas & Bank', icon: RefreshCw },
      { key: 'jurnal-umum', label: 'Jurnal Umum', icon: Scale },
      { key: 'buku-besar', label: 'Buku Besar', icon: BarChart3 },
      { key: 'neraca-saldo', label: 'Neraca Saldo', icon: TrendingUp },
    ],
  },
  {
    label: 'LAPORAN PSAK 109',
    items: [
      { key: 'posisi-keuangan', label: 'Posisi Keuangan', icon: FileText },
      { key: 'perubahan-dana', label: 'Perubahan Dana', icon: FileText },
      { key: 'arus-kas', label: 'Arus Kas', icon: FileText },
    ],
  },
  {
    label: 'REGULATOR & ARSIP',
    items: [
      { key: 'baznas', label: 'BAZNAS Kebumen', icon: Landmark },
      { key: 'arsip-digital', label: 'Arsip Digital', icon: Archive },
    ],
  },
  {
    label: 'SISTEM & ALAT',
    items: [
      { key: 'kalkulator-zakat', label: 'Kalkulator Zakat', icon: Calculator },
      { key: 'backup-restore', label: 'Backup & Restore', icon: Database },
      { key: 'audit-log', label: 'Log Aktivitas User', icon: History },
      { key: 'users', label: 'Manajemen Pengguna', icon: ShieldCheck },
      { key: 'settings', label: 'Pengaturan Sistem', icon: SettingsIcon },
    ],
  },
];

const titleMap: Record<string, string> = {
  dashboard: 'Ikhtisar Dashboard Utama',
  muzakki: 'Data Muzakki / Donatur',
  mustahik: 'Data Mustahik (Penerima 8 Asnaf)',
  penerimaan: 'Penerimaan Dana ZIS',
  penyaluran: 'Penyaluran Dana ZIS',
  operasional: 'Pengeluaran Operasional Amil',
  programs: 'Program Penyaluran ZIS',
  'collection-plans': 'Rencana Penghimpunan ZIS',
  'program-control': 'Kontrol & Monitor Program',
  baznas: 'Setoran & Laporan BAZNAS Kebumen',
  'arsip-digital': 'Arsip Digital & Bukti Transaksi',
  'kalkulator-zakat': 'Kalkulator Zakat PSAK 109',
  'audit-log': 'Log Aktivitas User (Audit Trail)',
  users: 'Manajemen Pengguna',
  settings: 'Pengaturan Sistem',
  'backup-restore': 'Backup & Restore Data',
  'chart-of-accounts': 'Bagan Akun (Chart of Accounts)',
  'buku-kas': 'Buku Kas Umum',
  'buku-besar': 'Buku Besar (General Ledger)',
  'neraca-saldo': 'Neraca Saldo (Trial Balance)',
  'mutasi-kas-bank': 'Mutasi Kas & Bank',
  'jurnal-umum': 'Jurnal Umum',
  'posisi-keuangan': 'Laporan Posisi Keuangan — PSAK 109',
  'perubahan-dana': 'Laporan Perubahan Dana — PSAK 109',
  'arus-kas': 'Laporan Arus Kas — PSAK 109',
};

const pageTitle = computed(() => titleMap[props.activeTab] || 'Dashboard');

const navigate = (tab: string) => {
  emit('navigate', tab);
  mobileOpen.value = false;
};

const logout = () => {
  emit('logout');
};
</script>

// frontend/src/components/Layout.tsx
import React, { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import {
  LayoutDashboard, Users, UserCheck, Target, Folder, ClipboardCheck,
  ArrowDownLeft, ArrowUpRight, TrendingDown,
  BookOpen, RefreshCw, Scale, FileText,
  BarChart3, TrendingUp, Activity,
  Building, Archive,
  Calculator, Database, History,
  LogOut, Menu, X, ChevronRight, UserCog, Settings as SettingsIcon,
} from 'lucide-react';

interface NavItem { key: string; label: string; icon: React.ReactNode; }
interface NavGroup { label: string; items: NavItem[]; }

const NAV_GROUPS: NavGroup[] = [
  { label: 'MENU UTAMA', items: [
    { key: 'dashboard', label: 'Ikhtisar Dashboard', icon: <LayoutDashboard size={16} /> },
  ]},
  { label: 'DATA MASTER', items: [
    { key: 'muzakki', label: 'Muzakki', icon: <Users size={16} /> },
    { key: 'mustahik', label: 'Mustahik', icon: <UserCheck size={16} /> },
  ]},
  { label: 'PERENCANAAN', items: [
    { key: 'collection-plans', label: 'Rencana Penghimpunan', icon: <Target size={16} /> },
    { key: 'programs', label: 'Program Penyaluran', icon: <Folder size={16} /> },
    { key: 'program-control', label: 'Kontrol Program', icon: <ClipboardCheck size={16} /> },
  ]},
  { label: 'TRANSAKSI', items: [
    { key: 'penerimaan', label: 'Penerimaan Dana', icon: <ArrowDownLeft size={16} /> },
    { key: 'penyaluran', label: 'Penyaluran Dana', icon: <ArrowUpRight size={16} /> },
    { key: 'operasional', label: 'Pengeluaran Operasional', icon: <TrendingDown size={16} /> },
  ]},
  { label: 'PEMBUKUAN', items: [
    { key: 'chart-of-accounts', label: 'Chart of Accounts', icon: <BookOpen size={16} /> },
    { key: 'buku-kas', label: 'Buku Kas Umum', icon: <FileText size={16} /> },
    { key: 'mutasi-kas-bank', label: 'Mutasi Kas & Bank', icon: <RefreshCw size={16} /> },
    { key: 'jurnal-umum', label: 'Jurnal Umum', icon: <Scale size={16} /> },
    { key: 'buku-besar', label: 'Buku Besar', icon: <BarChart3 size={16} /> },
    { key: 'neraca-saldo', label: 'Neraca Saldo', icon: <Activity size={16} /> },
  ]},
  { label: 'LAPORAN PSAK 109', items: [
    { key: 'posisi-keuangan', label: 'Posisi Keuangan', icon: <TrendingUp size={16} /> },
    { key: 'perubahan-dana', label: 'Perubahan Dana', icon: <BarChart3 size={16} /> },
    { key: 'arus-kas', label: 'Arus Kas', icon: <Activity size={16} /> },
  ]},
  { label: 'REGULATOR & ARSIP', items: [
    { key: 'baznas', label: 'BAZNAS Kebumen', icon: <Building size={16} /> },
    { key: 'arsip-digital', label: 'Arsip Digital', icon: <Archive size={16} /> },
  ]},
  { label: 'SISTEM & ALAT', items: [
    { key: 'kalkulator-zakat', label: 'Kalkulator Zakat', icon: <Calculator size={16} /> },
    { key: 'backup-restore', label: 'Backup & Restore', icon: <Database size={16} /> },
    { key: 'audit-log', label: 'Log Aktivitas User', icon: <History size={16} /> },
    { key: 'users', label: 'Manajemen Pengguna', icon: <UserCog size={16} /> },
    { key: 'settings', label: 'Pengaturan Sistem', icon: <SettingsIcon size={16} /> },
  ]},
];

interface LayoutProps { activePage: string; onNavigate: (page: string) => void; children: React.ReactNode; pageTitle?: string; }

export default function Layout({ activePage, onNavigate, children, pageTitle }: LayoutProps) {
  const { user, logout } = useAuth();
  const [mobileOpen, setMobileOpen] = useState(false);

  const ROLE_COLOR: Record<string, string> = {
    Admin: 'badge-red', Operator: 'badge-blue', Pimpinan: 'badge-orange', Auditor: 'badge-purple',
  };

  const activeItem = NAV_GROUPS.flatMap(g => g.items).find(i => i.key === activePage);
  const breadcrumb = `SIMZAKAT » ${activeItem?.label || 'Dashboard'}`;

  return (
    <div className="app-layout">
      {/* Mobile overlay */}
      {mobileOpen && <div onClick={() => setMobileOpen(false)} style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.6)', zIndex: 99 }} />}

      {/* SIDEBAR */}
      <aside className={`sidebar ${mobileOpen ? 'open' : ''}`}>
        {/* Header */}
        <div className="sidebar-header">
          <div className="sidebar-logo">
            <div className="sidebar-logo-icon">Z</div>
            <div className="sidebar-logo-text">
              <h2>SIMZAKAT</h2>
              <p>UPZ KEMENAG KEBUMEN</p>
            </div>
          </div>
          <div className="sidebar-user">
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
              <div>
                <div className="user-name">{user?.name || 'User'}</div>
                <div className="user-email">{user?.email}</div>
              </div>
              <span className={`badge ${ROLE_COLOR[user?.role || ''] || 'badge-gray'}`} style={{ fontSize: '10px' }}>{user?.role}</span>
            </div>
          </div>
        </div>

        {/* Navigation */}
        <nav className="sidebar-nav">
          {NAV_GROUPS.map((group) => (
            <div key={group.label}>
              <div className="nav-section-label">{group.label}</div>
              {group.items.map((item) => (
                <div
                  key={item.key}
                  className={`nav-item ${activePage === item.key ? 'active' : ''}`}
                  onClick={() => { onNavigate(item.key); setMobileOpen(false); }}
                >
                  {item.icon}
                  <span>{item.label}</span>
                  {activePage === item.key && <ChevronRight size={12} style={{ marginLeft: 'auto', opacity: 0.6 }} />}
                </div>
              ))}
            </div>
          ))}
        </nav>

        {/* Footer */}
        <div className="sidebar-footer">
          <button className="btn-logout" onClick={logout}>
            <LogOut size={14} />
            Keluar (Logout)
          </button>
        </div>
      </aside>

      {/* MAIN */}
      <div className="main-content">
        {/* Topbar */}
        <header className="topbar">
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
              <button onClick={() => setMobileOpen(!mobileOpen)} className="btn btn-ghost btn-sm" style={{ display: 'none' }}>
                {mobileOpen ? <X size={16} /> : <Menu size={16} />}
              </button>
              <div>
                <div className="topbar-title">{pageTitle || activeItem?.label || 'Dashboard'}</div>
                <div className="topbar-breadcrumb">{breadcrumb}</div>
              </div>
            </div>
          </div>
          <div className="topbar-badges">
            <span className={`badge ${ROLE_COLOR[user?.role || ''] || 'badge-gray'}`}>Hak Akses: {user?.role}</span>
            <span className="badge badge-green">● Sistem Aktif</span>
          </div>
        </header>

        {/* Content */}
        <main className="page-content">
          {children}
        </main>
      </div>
    </div>
  );
}
