// frontend-vue/src/views/BaznasKebumen.vue
<template>
  <div>
    <div class="section-header">
      <div>
        <h3>Setoran & Pengembalian BAZNAS Kebumen</h3>
        <p>Pencatatan arus dana setoran ZIS ke BAZNAS Kab. Kebumen dan pengembalian hak amil/mustahik</p>
      </div>
      <button class="btn btn-primary" @click="isModalOpen = true">
        <Plus :size="14" /> + Catat Transaksi BAZNAS
      </button>
    </div>

    <div class="card">
      <div class="table-container">
        <table>
          <thead>
            <tr>
              <th>TANGGAL</th>
              <th>JENIS ARUS</th>
              <th>KATEGORI DANA</th>
              <th>REKENING BAZNAS / UPZ</th>
              <th>KETERANGAN</th>
              <th class="text-right">NOMINAL</th>
              <th>STATUS</th>
              <th class="text-center">AKSI</th>
            </tr>
          </thead>
          <tbody>
            <tr v-if="loading && !data.length">
              <td colspan="8" class="text-center" style="padding: 30px;">
                <span class="loading-spinner" style="width: 18px; height: 18px; margin-right: 8px;"></span>
                Memuat data...
              </td>
            </tr>
            <tr v-else-if="!data.length">
              <td colspan="8" class="text-center" style="padding: 40px; color: #64748b;">
                Belum ada riwayat transaksi dengan BAZNAS Kebumen.
              </td>
            </tr>
            <tr v-for="item in data" :key="item.id">
              <td style="white-space: nowrap; font-size: 12px;">{{ formatDate(item.date) }}</td>
              <td>
                <span :class="['badge', item.type === 'setor' ? 'badge-orange' : 'badge-green']">
                  <ArrowUpRight v-if="item.type === 'setor'" :size="12" style="margin-right: 3px;" />
                  <ArrowDownLeft v-else :size="12" style="margin-right: 3px;" />
                  {{ item.type === 'setor' ? 'Setoran ke BAZNAS' : 'Pengembalian BAZNAS' }}
                </span>
              </td>
              <td>{{ item.category || '-' }}</td>
              <td style="font-size: 12px;">{{ item.bank_account }}</td>
              <td style="max-width: 200px; font-size: 12px;">{{ item.description }}</td>
              <td class="text-right font-bold" :style="{ color: item.type === 'setor' ? '#d97706' : '#059669' }">
                {{ formatRp(item.amount) }}
              </td>
              <td>
                <span :class="['status-badge', `status-${item.status?.toLowerCase() || 'draft'}`]">
                  {{ item.status }}
                </span>
              </td>
              <td class="text-center">
                <button v-if="item.status === 'Draft'" class="btn btn-primary btn-xs" @click="handleApprove(item.id)">
                  <Check :size="12" style="margin-right: 2px;" /> Setujui
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <!-- Modal Form -->
    <div v-if="isModalOpen" class="modal-overlay" @click="isModalOpen = false">
      <div class="modal" @click.stop>
        <div class="modal-header">
          <h3>+ Catat Transaksi BAZNAS Kebumen</h3>
          <button class="btn-close" @click="isModalOpen = false">
            <X :size="16" />
          </button>
        </div>
        <form @submit.prevent="handleSubmit">
          <div class="modal-body">
            <div class="form-grid-2">
              <div class="form-group">
                <label class="form-label">Tanggal Transaksi<span class="required">*</span></label>
                <input type="date" class="form-input" v-model="form.date" required />
              </div>
              <div class="form-group">
                <label class="form-label">Jenis Arus Transaksi<span class="required">*</span></label>
                <select class="form-select" v-model="form.type">
                  <option value="setor">Setoran ZIS UPZ ke BAZNAS Kebumen</option>
                  <option value="pengembalian">Pengembalian Hak Amil / Penyaluran dari BAZNAS</option>
                </select>
              </div>
            </div>

            <div class="form-grid-2">
              <div class="form-group">
                <label class="form-label">Kategori Dana</label>
                <input type="text" class="form-input" placeholder="Contoh: Zakat Mal ASN" v-model="form.category" />
              </div>
              <div class="form-group">
                <label class="form-label">Nominal (Rp)<span class="required">*</span></label>
                <input type="number" class="form-input" placeholder="Contoh: 25000000" v-model="form.amount" required />
              </div>
            </div>

            <div class="form-group">
              <label class="form-label">Rekening Bank Tujuan / Sumber</label>
              <select class="form-select" v-model="form.bank_account">
                <option value="Bank Jateng Syariah - 5027127127 (BAZNAS Kebumen)">
                  Bank Jateng Syariah - 5027127127 (BAZNAS Kebumen)
                </option>
                <option
                  v-for="b in bankAccounts"
                  :key="b.id"
                  :value="`${b.bank_name} - ${b.account_number} (${b.account_holder})`"
                >
                  {{ b.bank_name }} - {{ b.account_number }} ({{ b.account_holder }})
                </option>
              </select>
            </div>

            <div class="form-group">
              <label class="form-label">Keterangan / Uraian<span class="required">*</span></label>
              <textarea class="form-textarea" rows="2" placeholder="Tuliskan keterangan..." v-model="form.description" required></textarea>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" @click="isModalOpen = false">Batal</button>
            <button type="submit" class="btn btn-primary">
              <Save :size="14" /> Simpan Transaksi
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import api, { formatRp, formatDate } from '../lib/api';
import { Plus, ArrowUpRight, ArrowDownLeft, Check, X, Save } from '@lucide/vue';

const data = ref<any[]>([]);
const bankAccounts = ref<any[]>([]);
const loading = ref(false);
const isModalOpen = ref(false);

const form = ref({
  date: new Date().toISOString().slice(0, 10),
  type: 'setor',
  category: 'Zakat Mal ASN',
  amount: '',
  bank_account: 'Bank Jateng Syariah - 5027127127 (BAZNAS Kebumen)',
  description: '',
});

const fetchData = async () => {
  loading.value = true;
  try {
    const res = await api.get('/baznas-transactions');
    data.value = res.data?.data || [];
  } catch (err) {
    console.error(err);
  } finally {
    loading.value = false;
  }
};

const handleSubmit = async () => {
  try {
    await api.post('/baznas-transactions', {
      ...form.value,
      amount: Number(form.value.amount),
    });
    isModalOpen.value = false;
    fetchData();
  } catch (err: any) {
    alert(err.response?.data?.message || 'Gagal menyimpan.');
  }
};

const handleApprove = async (id: number) => {
  if (!confirm('Setujui transaksi setoran/pengembalian BAZNAS ini?')) return;
  try {
    await api.patch(`/baznas-transactions/${id}/approve`);
    fetchData();
  } catch (err: any) {
    alert(err.response?.data?.message || 'Gagal menyetujui.');
  }
};

const fetchBankAccounts = async () => {
  try {
    const res = await api.get('/bank-accounts');
    bankAccounts.value = res.data || [];
  } catch (err) {
    console.error(err);
  }
};

onMounted(() => {
  fetchData();
  fetchBankAccounts();
});
</script>

// frontend/src/pages/BaznasKebumen.tsx
import React, { useState, useEffect } from 'react';
import api, { formatRp, formatDate } from '../lib/api';
import { Building, PlusCircle, CheckCircle, X, ArrowUpRight, ArrowDownLeft } from 'lucide-react';

export default function BaznasKebumen() {
  const [data, setData] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [isModalOpen, setIsModalOpen] = useState(false);

  const [formData, setFormData] = useState({
    date: new Date().toISOString().slice(0, 10),
    type: 'setor',
    category: 'Zakat Mal ASN',
    amount: '',
    source_payment_method: 'bank',
    bank_account: 'Bank Jateng Syariah - 5027127127 (BAZNAS Kebumen)',
    description: '',
  });

  const fetchData = async () => {
    setLoading(true);
    try {
      const res = await api.get('/baznas-transactions');
      setData(res.data?.data || []);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      await api.post('/baznas-transactions', {
        ...formData,
        amount: Number(formData.amount),
      });
      setIsModalOpen(false);
      fetchData();
    } catch (err: any) {
      alert(err.response?.data?.message || 'Gagal menyimpan data.');
    }
  };

  const handleApprove = async (id: number) => {
    if (!confirm('Setujui transaksi setoran/pengembalian BAZNAS ini?')) return;
    try {
      await api.patch(`/baznas-transactions/${id}/approve`);
      fetchData();
    } catch (err: any) {
      alert(err.response?.data?.message || 'Gagal menyetujui.');
    }
  };

  return (
    <div>
      <div className="section-header">
        <div>
          <h3>Setoran & Pengembalian BAZNAS Kebumen</h3>
          <p>Pencatatan arus dana setoran ZIS ke BAZNAS Kab. Kebumen dan pengembalian hak amil/mustahik</p>
        </div>
        <button className="btn btn-primary" onClick={() => setIsModalOpen(true)}>
          <PlusCircle size={14} /> + Catat Transaksi BAZNAS
        </button>
      </div>

      <div className="card">
        <div className="table-container">
          <table>
            <thead>
              <tr>
                <th>TANGGAL</th>
                <th>JENIS ARUS</th>
                <th>KATEGORI DANA</th>
                <th>REKENING BAZNAS / UPZ</th>
                <th>KETERANGAN</th>
                <th className="text-right">NOMINAL</th>
                <th>STATUS</th>
                <th className="text-center">AKSI</th>
              </tr>
            </thead>
            <tbody>
              {loading && data.length === 0 ? (
                <tr>
                  <td colSpan={8} className="text-center" style={{ padding: '30px' }}>
                    <span className="loading-spinner" style={{ width: 18, height: 18, marginRight: 8 }} />
                    Memuat data...
                  </td>
                </tr>
              ) : data.length === 0 ? (
                <tr>
                  <td colSpan={8} className="text-center" style={{ padding: '40px', color: 'var(--text-muted)' }}>
                    Belum ada riwayat transaksi dengan BAZNAS Kebumen.
                  </td>
                </tr>
              ) : (
                data.map(item => (
                  <tr key={item.id}>
                    <td style={{ whiteSpace: 'nowrap', fontSize: '12px' }}>{formatDate(item.date)}</td>
                    <td>
                      <span className={`badge ${item.type === 'setor' ? 'badge-orange' : 'badge-green'}`}>
                        {item.type === 'setor' ? '↑ Setoran ke BAZNAS' : '↓ Pengembalian BAZNAS'}
                      </span>
                    </td>
                    <td>{item.category || '-'}</td>
                    <td style={{ fontSize: '12px' }}>{item.bank_account}</td>
                    <td style={{ maxWidth: '200px', fontSize: '12px' }}>{item.description}</td>
                    <td className="text-right font-bold" style={{ color: item.type === 'setor' ? 'var(--accent-orange)' : 'var(--accent-green)' }}>
                      {formatRp(item.amount)}
                    </td>
                    <td>
                      <span className={`status-badge status-${item.status?.toLowerCase() || 'draft'}`}>
                        {item.status}
                      </span>
                    </td>
                    <td className="text-center">
                      {item.status === 'Draft' && (
                        <button className="btn btn-primary btn-xs" onClick={() => handleApprove(item.id)}>
                          Setujui
                        </button>
                      )}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {isModalOpen && (
        <div className="modal-overlay" onClick={() => setIsModalOpen(false)}>
          <div className="modal" onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <h3>+ Catat Transaksi BAZNAS Kebumen</h3>
              <button className="btn-close" onClick={() => setIsModalOpen(false)}><X size={16} /></button>
            </div>
            <form onSubmit={handleSubmit}>
              <div className="modal-body">
                <div className="form-grid-2">
                  <div className="form-group">
                    <label className="form-label">Tanggal Transaksi<span className="required">*</span></label>
                    <input
                      type="date"
                      className="form-input"
                      value={formData.date}
                      onChange={e => setFormData({ ...formData, date: e.target.value })}
                      required
                    />
                  </div>
                  <div className="form-group">
                    <label className="form-label">Jenis Arus Transaksi<span className="required">*</span></label>
                    <select
                      className="form-select"
                      value={formData.type}
                      onChange={e => setFormData({ ...formData, type: e.target.value })}
                    >
                      <option value="setor">Setoran ZIS UPZ ke BAZNAS Kebumen</option>
                      <option value="pengembalian">Pengembalian Hak Amil / Penyaluran dari BAZNAS</option>
                    </select>
                  </div>
                </div>

                <div className="form-grid-2">
                  <div className="form-group">
                    <label className="form-label">Kategori Dana</label>
                    <input
                      type="text"
                      className="form-input"
                      value={formData.category}
                      onChange={e => setFormData({ ...formData, category: e.target.value })}
                      placeholder="Contoh: Zakat Mal ASN / Infak"
                    />
                  </div>
                  <div className="form-group">
                    <label className="form-label">Nominal (Rp)<span className="required">*</span></label>
                    <input
                      type="number"
                      className="form-input"
                      value={formData.amount}
                      onChange={e => setFormData({ ...formData, amount: e.target.value })}
                      placeholder="Contoh: 25000000"
                      required
                    />
                  </div>
                </div>

                <div className="form-group">
                  <label className="form-label">Rekening Bank Tujuan / Sumber</label>
                  <input
                    type="text"
                    className="form-input"
                    value={formData.bank_account}
                    onChange={e => setFormData({ ...formData, bank_account: e.target.value })}
                    placeholder="Contoh: Bank Jateng Syariah 5027127127"
                  />
                </div>

                <div className="form-group">
                  <label className="form-label">Keterangan / Uraian<span className="required">*</span></label>
                  <textarea
                    className="form-textarea"
                    rows={2}
                    value={formData.description}
                    onChange={e => setFormData({ ...formData, description: e.target.value })}
                    placeholder="Tuliskan keterangan..."
                    required
                  />
                </div>
              </div>
              <div className="modal-footer">
                <button type="button" className="btn btn-secondary" onClick={() => setIsModalOpen(false)}>Batal</button>
                <button type="submit" className="btn btn-primary">Simpan Transaksi</button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
