// frontend-vue/src/views/KalkulatorZakat.vue
<template>
  <div>
    <div class="section-header">
      <div>
        <h3>Kalkulator Zakat PSAK 109</h3>
        <p>Perhitungan nisab dan kewajiban zakat sesuai fatwa MUI dan regulasi BAZNAS</p>
      </div>
    </div>

    <div style="max-width: 800px; margin: 0 auto;">
      <!-- Tab Buttons -->
      <div style="display: flex; gap: 8px; margin-bottom: 20px; flex-wrap: wrap;">
        <button
          v-for="t in tabs"
          :key="t.key"
          :class="['btn', activeTab === t.key ? 'btn-primary' : 'btn-ghost']"
          @click="activeTab = t.key"
        >
          {{ t.label }}
        </button>
      </div>

      <!-- Tab Gaji -->
      <div v-if="activeTab === 'gaji'" class="card">
        <h4 style="font-size: 15px; font-weight: 700; margin-bottom: 16px;">Simulasi Zakat Penghasilan (Bulan Berjalan)</h4>
        <div class="form-grid-2">
          <div class="form-group">
            <label class="form-label">Gaji Pokok (Rp)</label>
            <input type="number" class="form-input" placeholder="Contoh: 4500000" v-model="gajiPokok" />
          </div>
          <div class="form-group">
            <label class="form-label">Tunjangan Lainnya (Rp)</label>
            <input type="number" class="form-input" placeholder="Contoh: 2000000" v-model="tunjangan" />
          </div>
        </div>
        <div class="form-group">
          <label class="form-label">Pengurang / Kebutuhan Pokok Mendesak (Rp)</label>
          <input type="number" class="form-input" placeholder="Contoh: 0" v-model="potonganHutang" />
        </div>

        <div style="background: #ecfdf5; border: 1px solid #a7f3d0; border-radius: var(--radius-sm); padding: 16px; margin-top: 16px;">
          <div style="display: flex; justify-content: space-between; font-size: 12px; margin-bottom: 8px;">
            <span style="color: #64748b;">Nisab Emas 85gr / Bulan:</span>
            <strong>{{ formatRp(nisabBulanan) }}</strong>
          </div>
          <div style="display: flex; justify-content: space-between; font-size: 12px; margin-bottom: 8px;">
            <span style="color: #64748b;">Penghasilan Bersih:</span>
            <strong>{{ formatRp(hasilGaji.netto) }}</strong>
          </div>
          <div class="divider" style="margin: 10px 0;"></div>
          <div style="display: flex; justify-content: space-between; align-items: center;">
            <div>
              <div style="font-size: 13px; font-weight: 700;">Kewajiban Zakat (2.5%):</div>
              <span :class="['badge', hasilGaji.wajib ? 'badge-green' : 'badge-gray']" style="font-size: 10px; margin-top: 4px;">
                {{ hasilGaji.wajib ? '✓ Wajib Zakat (Mencapai Nisab)' : 'Belum Mencapai Nisab (Disunnahkan Infak)' }}
              </span>
            </div>
            <div style="font-size: 22px; font-weight: 800; color: #059669;">
              {{ formatRp(hasilGaji.zakat) }}
            </div>
          </div>
        </div>
      </div>

      <!-- Tab TPG -->
      <div v-else-if="activeTab === 'tpg'" class="card">
        <h4 style="font-size: 15px; font-weight: 700; margin-bottom: 16px;">Zakat Tunjangan Profesi Guru & Tukin</h4>
        <div class="form-group">
          <label class="form-label">Nominal TPG / Tukin Diterima (Rp)</label>
          <input type="number" class="form-input" placeholder="Contoh: 12000000" v-model="nominalTukin" />
        </div>

        <div style="background: #eff6ff; border: 1px solid #bfdbfe; border-radius: var(--radius-sm); padding: 16px; margin-top: 16px;">
          <div style="display: flex; justify-content: space-between; align-items: center;">
            <div>
              <div style="font-size: 13px; font-weight: 700;">Potongan Zakat Langsung (2.5%):</div>
              <p style="font-size: 11px; color: #64748b;">Dihimpun UPZ Kemenag untuk disalurkan ke 8 asnaf</p>
            </div>
            <div style="font-size: 22px; font-weight: 800; color: #2563eb;">
              {{ formatRp(hasilTpg.zakat) }}
            </div>
          </div>
        </div>
      </div>

      <!-- Tab Fitrah -->
      <div v-else-if="activeTab === 'fitrah'" class="card">
        <h4 style="font-size: 15px; font-weight: 700; margin-bottom: 16px;">Zakat Fitrah (Ramadhan)</h4>
        <div class="form-grid-2">
          <div class="form-group">
            <label class="form-label">Jumlah Jiwa / Tanggungan</label>
            <input type="number" class="form-input" min="1" v-model="jumlahJiwa" />
          </div>
          <div class="form-group">
            <label class="form-label">Standar Harga Beras per Kg (Rp)</label>
            <input type="number" class="form-input" v-model="hargaBerasKg" />
          </div>
        </div>

        <div style="background: #ecfdf5; border: 1px solid #a7f3d0; border-radius: var(--radius-sm); padding: 16px; margin-top: 16px;">
          <div style="display: flex; justify-content: space-between; font-size: 12px; margin-bottom: 8px;">
            <span style="color: #64748b;">Beras (2.5 Kg / Jiwa):</span>
            <strong>{{ hasilFitrah.berasKg }} Kg Beras</strong>
          </div>
          <div style="display: flex; justify-content: space-between; font-size: 12px; margin-bottom: 8px;">
            <span style="color: #64748b;">Nominal per Jiwa:</span>
            <strong>{{ formatRp(hasilFitrah.perJiwa) }}</strong>
          </div>
          <div class="divider" style="margin: 10px 0;"></div>
          <div style="display: flex; justify-content: space-between; align-items: center;">
            <div>
              <div style="font-size: 13px; font-weight: 700;">Total Konversi Uang ({{ hasilFitrah.jiwa }} Jiwa):</div>
            </div>
            <div style="font-size: 22px; font-weight: 800; color: #059669;">
              {{ formatRp(hasilFitrah.total) }}
            </div>
          </div>
        </div>
      </div>

      <!-- Tab Emas -->
      <div v-else-if="activeTab === 'emas'" class="card">
        <h4 style="font-size: 15px; font-weight: 700; margin-bottom: 16px;">Zakat Emas & Tabungan (Haul 1 Tahun)</h4>
        <div class="form-grid-2">
          <div class="form-group">
            <label class="form-label">Total Emas Simpanan (Gram)</label>
            <input type="number" class="form-input" placeholder="Contoh: 100" v-model="totalEmasGram" />
          </div>
          <div class="form-group">
            <label class="form-label">Harga Emas Saat Ini / Gram (Rp)</label>
            <input type="number" class="form-input" v-model="hargaEmasGram" />
          </div>
        </div>
        <div class="form-group">
          <label class="form-label">Total Uang Tabungan / Deposito Mengendap (Rp)</label>
          <input type="number" class="form-input" placeholder="Contoh: 50000000" v-model="totalTabungan" />
        </div>

        <div style="background: #fffbeb; border: 1px solid #fde68a; border-radius: var(--radius-sm); padding: 16px; margin-top: 16px;">
          <div style="display: flex; justify-content: space-between; font-size: 12px; margin-bottom: 8px;">
            <span style="color: #64748b;">Nisab Emas 85 Gram (Tahunan):</span>
            <strong>{{ formatRp(hasilEmas.nisabTahunan) }}</strong>
          </div>
          <div style="display: flex; justify-content: space-between; font-size: 12px; margin-bottom: 8px;">
            <span style="color: #64748b;">Total Nilai Harta:</span>
            <strong>{{ formatRp(hasilEmas.totalAset) }}</strong>
          </div>
          <div class="divider" style="margin: 10px 0;"></div>
          <div style="display: flex; justify-content: space-between; align-items: center;">
            <div>
              <div style="font-size: 13px; font-weight: 700;">Kewajiban Zakat Mal (2.5%):</div>
              <span :class="['badge', hasilEmas.wajib ? 'badge-green' : 'badge-gray']" style="font-size: 10px; margin-top: 4px;">
                {{ hasilEmas.wajib ? '✓ Wajib Zakat Mal' : 'Belum Mencapai Nisab' }}
              </span>
            </div>
            <div style="font-size: 22px; font-weight: 800; color: #d97706;">
              {{ formatRp(hasilEmas.zakat) }}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { formatRp } from '../lib/api';

const activeTab = ref('gaji');

const tabs = [
  { key: 'gaji', label: 'Zakat Penghasilan / Gaji ASN' },
  { key: 'tpg', label: 'Zakat TPG & Tukin PNS' },
  { key: 'fitrah', label: 'Zakat Fitrah Ramadhan' },
  { key: 'emas', label: 'Zakat Emas & Tabungan' },
];

const gajiPokok = ref('');
const tunjangan = ref('');
const potonganHutang = ref('');
const nominalTukin = ref('');
const jumlahJiwa = ref('1');
const hargaBerasKg = ref('16000');
const totalEmasGram = ref('');
const hargaEmasGram = ref('1500000');
const totalTabungan = ref('');

const nisabBulanan = computed(() => (85 * Number(hargaEmasGram.value || 1500000)) / 12);

const hasilGaji = computed(() => {
  const totalBruto = (Number(gajiPokok.value) || 0) + (Number(tunjangan.value) || 0);
  const netto = Math.max(0, totalBruto - (Number(potonganHutang.value) || 0));
  const wajib = netto >= nisabBulanan.value;
  const zakat = wajib ? netto * 0.025 : 0;
  return { totalBruto, netto, wajib, zakat };
});

const hasilTpg = computed(() => {
  const bruto = Number(nominalTukin.value) || 0;
  const wajib = bruto > 0;
  const zakat = wajib ? bruto * 0.025 : 0;
  return { bruto, wajib, zakat };
});

const hasilFitrah = computed(() => {
  const jiwa = Number(jumlahJiwa.value) || 1;
  const perJiwa = 2.5 * (Number(hargaBerasKg.value) || 16000);
  const total = jiwa * perJiwa;
  const berasKg = jiwa * 2.5;
  return { jiwa, perJiwa, total, berasKg };
});

const hasilEmas = computed(() => {
  const emas = Number(totalEmasGram.value) || 0;
  const hrg = Number(hargaEmasGram.value) || 1500000;
  const tab = Number(totalTabungan.value) || 0;
  const totalAset = (emas * hrg) + tab;
  const nisabTahunan = 85 * hrg;
  const wajib = totalAset >= nisabTahunan;
  const zakat = wajib ? totalAset * 0.025 : 0;
  return { totalAset, nisabTahunan, wajib, zakat };
});
</script>

// frontend/src/pages/KalkulatorZakat.tsx
import React, { useState } from 'react';
import { formatRp } from '../lib/api';
import { Calculator, CheckCircle, ArrowRight, ShieldCheck } from 'lucide-react';

export default function KalkulatorZakat() {
  const [activeTab, setActiveTab] = useState<'gaji' | 'tpg' | 'fitrah' | 'emas'>('gaji');

  // Gaji ASN
  const [gajiPokok, setGajiPokok] = useState('');
  const [tunjangan, setTunjangan] = useState('');
  const [potonganHutang, setPotonganHutang] = useState('');

  // TPG / Tukin
  const [nominalTukin, setNominalTukin] = useState('');

  // Fitrah
  const [jumlahJiwa, setJumlahJiwa] = useState('1');
  const [hargaBerasKg, setHargaBerasKg] = useState('16000'); // 2.5 kg x 16.000 = 40.000/jiwa

  // Emas / Tabungan
  const [totalEmasGram, setTotalEmasGram] = useState('');
  const [hargaEmasGram, setHargaEmasGram] = useState('1500000');
  const [totalTabungan, setTotalTabungan] = useState('');

  // Perhitungan
  const nisabBulanan = (85 * Number(hargaEmasGram || 1500000)) / 12;

  const hitungGaji = () => {
    const totalBruto = (Number(gajiPokok) || 0) + (Number(tunjangan) || 0);
    const netto = Math.max(0, totalBruto - (Number(potonganHutang) || 0));
    const wajib = netto >= nisabBulanan;
    const zakat = wajib ? netto * 0.025 : 0;
    return { totalBruto, netto, wajib, zakat };
  };

  const hitungTpg = () => {
    const bruto = Number(nominalTukin) || 0;
    const wajib = bruto > 0;
    const zakat = wajib ? bruto * 0.025 : 0;
    return { bruto, wajib, zakat };
  };

  const hitungFitrah = () => {
    const jiwa = Number(jumlahJiwa) || 1;
    const perJiwa = 2.5 * (Number(hargaBerasKg) || 16000);
    const total = jiwa * perJiwa;
    const berasKg = jiwa * 2.5;
    return { jiwa, perJiwa, total, berasKg };
  };

  const hitungEmas = () => {
    const emas = Number(totalEmasGram) || 0;
    const hrg = Number(hargaEmasGram) || 1500000;
    const tab = Number(totalTabungan) || 0;
    const totalAset = (emas * hrg) + tab;
    const nisabTahunan = 85 * hrg;
    const wajib = totalAset >= nisabTahunan;
    const zakat = wajib ? totalAset * 0.025 : 0;
    return { totalAset, nisabTahunan, wajib, zakat };
  };

  return (
    <div>
      <div className="section-header">
        <div>
          <h3>Kalkulator Zakat PSAK 109</h3>
          <p>Perhitungan nisab dan kewajiban zakat sesuai fatwa MUI dan regulasi BAZNAS</p>
        </div>
      </div>

      <div style={{ maxWidth: '800px', margin: '0 auto' }}>
        {/* Tab Buttons */}
        <div style={{ display: 'flex', gap: '8px', marginBottom: '20px', flexWrap: 'wrap' }}>
          {[
            { key: 'gaji', label: 'Zakat Penghasilan / Gaji ASN' },
            { key: 'tpg', label: 'Zakat TPG & Tukin PNS' },
            { key: 'fitrah', label: 'Zakat Fitrah Ramadhan' },
            { key: 'emas', label: 'Zakat Emas & Tabungan' },
          ].map(t => (
            <button
              key={t.key}
              className={`btn ${activeTab === t.key ? 'btn-primary' : 'btn-ghost'}`}
              onClick={() => setActiveTab(t.key as any)}
            >
              {t.label}
            </button>
          ))}
        </div>

        {/* Tab Gaji */}
        {activeTab === 'gaji' && (() => {
          const res = hitungGaji();
          return (
            <div className="card">
              <h4 style={{ fontSize: '15px', fontWeight: 700, marginBottom: '16px' }}>Simulasi Zakat Penghasilan (Bulan Berjalan)</h4>
              <div className="form-grid-2">
                <div className="form-group">
                  <label className="form-label">Gaji Pokok (Rp)</label>
                  <input type="number" className="form-input" placeholder="Contoh: 4500000" value={gajiPokok} onChange={e => setGajiPokok(e.target.value)} />
                </div>
                <div className="form-group">
                  <label className="form-label">Tunjangan Lainnya (Rp)</label>
                  <input type="number" className="form-input" placeholder="Contoh: 2000000" value={tunjangan} onChange={e => setTunjangan(e.target.value)} />
                </div>
              </div>
              <div className="form-group">
                <label className="form-label">Pengurang / Kebutuhan Pokok Mendesak (Rp)</label>
                <input type="number" className="form-input" placeholder="Contoh: 0" value={potonganHutang} onChange={e => setPotonganHutang(e.target.value)} />
              </div>

              <div style={{ background: 'rgba(0,196,140,0.08)', border: '1px solid rgba(0,196,140,0.2)', borderRadius: 'var(--radius-sm)', padding: '16px', marginTop: '16px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px', marginBottom: '8px' }}>
                  <span style={{ color: 'var(--text-muted)' }}>Nisab Emas 85gr / Bulan:</span>
                  <strong>{formatRp(nisabBulanan)}</strong>
                </div>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px', marginBottom: '8px' }}>
                  <span style={{ color: 'var(--text-muted)' }}>Penghasilan Bersih:</span>
                  <strong>{formatRp(res.netto)}</strong>
                </div>
                <div className="divider" style={{ margin: '10px 0' }} />
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <div>
                    <div style={{ fontSize: '13px', fontWeight: 600 }}>Kewajiban Zakat (2.5%):</div>
                    <span className={`badge ${res.wajib ? 'badge-green' : 'badge-gray'}`} style={{ fontSize: '10px', marginTop: '4px' }}>
                      {res.wajib ? '✓ Wajib Zakat (Mencapai Nisab)' : 'Belum Mencapai Nisab (Disunnahkan Infak)'}
                    </span>
                  </div>
                  <div style={{ fontSize: '20px', fontWeight: 800, color: 'var(--accent-green)' }}>
                    {formatRp(res.zakat)}
                  </div>
                </div>
              </div>
            </div>
          );
        })()}

        {/* Tab TPG / Tukin */}
        {activeTab === 'tpg' && (() => {
          const res = hitungTpg();
          return (
            <div className="card">
              <h4 style={{ fontSize: '15px', fontWeight: 700, marginBottom: '16px' }}>Zakat Tunjangan Profesi Guru & Tukin</h4>
              <div className="form-group">
                <label className="form-label">Nominal TPG / Tukin Diterima (Rp)</label>
                <input type="number" className="form-input" placeholder="Contoh: 12000000" value={nominalTukin} onChange={e => setNominalTukin(e.target.value)} />
              </div>

              <div style={{ background: 'rgba(78,135,255,0.08)', border: '1px solid rgba(78,135,255,0.2)', borderRadius: 'var(--radius-sm)', padding: '16px', marginTop: '16px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <div>
                    <div style={{ fontSize: '13px', fontWeight: 600 }}>Potongan Zakat Langsung (2.5%):</div>
                    <p style={{ fontSize: '11px', color: 'var(--text-muted)' }}>Dihimpun UPZ Kemenag untuk disalurkan ke asnaf</p>
                  </div>
                  <div style={{ fontSize: '20px', fontWeight: 800, color: 'var(--accent-blue)' }}>
                    {formatRp(res.zakat)}
                  </div>
                </div>
              </div>
            </div>
          );
        })()}

        {/* Tab Fitrah */}
        {activeTab === 'fitrah' && (() => {
          const res = hitungFitrah();
          return (
            <div className="card">
              <h4 style={{ fontSize: '15px', fontWeight: 700, marginBottom: '16px' }}>Zakat Fitrah (Ramadhan)</h4>
              <div className="form-grid-2">
                <div className="form-group">
                  <label className="form-label">Jumlah Jiwa / Tanggungan</label>
                  <input type="number" className="form-input" min="1" value={jumlahJiwa} onChange={e => setJumlahJiwa(e.target.value)} />
                </div>
                <div className="form-group">
                  <label className="form-label">Standar Harga Beras per Kg (Rp)</label>
                  <input type="number" className="form-input" value={hargaBerasKg} onChange={e => setHargaBerasKg(e.target.value)} />
                </div>
              </div>

              <div style={{ background: 'rgba(0,196,140,0.08)', border: '1px solid rgba(0,196,140,0.2)', borderRadius: 'var(--radius-sm)', padding: '16px', marginTop: '16px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px', marginBottom: '8px' }}>
                  <span style={{ color: 'var(--text-muted)' }}>Beras (2.5 Kg / Jiwa):</span>
                  <strong>{res.berasKg} Kg Beras</strong>
                </div>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px', marginBottom: '8px' }}>
                  <span style={{ color: 'var(--text-muted)' }}>Nominal per Jiwa:</span>
                  <strong>{formatRp(res.perJiwa)}</strong>
                </div>
                <div className="divider" style={{ margin: '10px 0' }} />
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <div>
                    <div style={{ fontSize: '13px', fontWeight: 600 }}>Total Konversi Uang ({res.jiwa} Jiwa):</div>
                  </div>
                  <div style={{ fontSize: '20px', fontWeight: 800, color: 'var(--accent-green)' }}>
                    {formatRp(res.total)}
                  </div>
                </div>
              </div>
            </div>
          );
        })()}

        {/* Tab Emas */}
        {activeTab === 'emas' && (() => {
          const res = hitungEmas();
          return (
            <div className="card">
              <h4 style={{ fontSize: '15px', fontWeight: 700, marginBottom: '16px' }}>Zakat Emas & Tabungan (Haul 1 Tahun)</h4>
              <div className="form-grid-2">
                <div className="form-group">
                  <label className="form-label">Total Emas Simpanan (Gram)</label>
                  <input type="number" className="form-input" placeholder="Contoh: 100" value={totalEmasGram} onChange={e => setTotalEmasGram(e.target.value)} />
                </div>
                <div className="form-group">
                  <label className="form-label">Harga Emas Saat Ini / Gram (Rp)</label>
                  <input type="number" className="form-input" value={hargaEmasGram} onChange={e => setHargaEmasGram(e.target.value)} />
                </div>
              </div>
              <div className="form-group">
                <label className="form-label">Total Uang Tabungan / Deposito Mengendap (Rp)</label>
                <input type="number" className="form-input" placeholder="Contoh: 50000000" value={totalTabungan} onChange={e => setTotalTabungan(e.target.value)} />
              </div>

              <div style={{ background: 'rgba(245,158,11,0.08)', border: '1px solid rgba(245,158,11,0.2)', borderRadius: 'var(--radius-sm)', padding: '16px', marginTop: '16px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px', marginBottom: '8px' }}>
                  <span style={{ color: 'var(--text-muted)' }}>Nisab Emas 85 Gram (Tahunan):</span>
                  <strong>{formatRp(res.nisabTahunan)}</strong>
                </div>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px', marginBottom: '8px' }}>
                  <span style={{ color: 'var(--text-muted)' }}>Total Nilai Harta:</span>
                  <strong>{formatRp(res.totalAset)}</strong>
                </div>
                <div className="divider" style={{ margin: '10px 0' }} />
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <div>
                    <div style={{ fontSize: '13px', fontWeight: 600 }}>Kewajiban Zakat Mal (2.5%):</div>
                    <span className={`badge ${res.wajib ? 'badge-green' : 'badge-gray'}`} style={{ fontSize: '10px', marginTop: '4px' }}>
                      {res.wajib ? '✓ Wajib Zakat Mal' : 'Belum Mencapai Nisab'}
                    </span>
                  </div>
                  <div style={{ fontSize: '20px', fontWeight: 800, color: 'var(--accent-orange)' }}>
                    {formatRp(res.zakat)}
                  </div>
                </div>
              </div>
            </div>
          );
        })()}
      </div>
    </div>
  );
}
