// frontend-vue/src/views/Programs.vue
<template>
  <div>
    <div class="section-header">
      <div>
        <h3>Program Penyaluran ZIS</h3>
        <p>Daftar alokasi program kerja penyaluran UPZ Kemenag</p>
      </div>
      <button class="btn btn-primary" @click="openModal()">
        <Plus :size="14" /> + Tambah Program
      </button>
    </div>

    <div class="card">
      <div class="table-container">
        <table>
          <thead>
            <tr>
              <th>NAMA PROGRAM</th>
              <th>BIDANG</th>
              <th>SUMBER DANA</th>
              <th>PIC / WAKTU</th>
              <th class="text-right">TARGET ANGGARAN</th>
              <th class="text-right">REALISASI</th>
              <th class="text-center">AKSI</th>
            </tr>
          </thead>
          <tbody>
            <tr v-if="loading && !data.length">
              <td colspan="7" class="text-center" style="padding: 30px;">
                <span class="loading-spinner" style="width: 18px; height: 18px; margin-right: 8px;"></span>
                Memuat program...
              </td>
            </tr>
            <tr v-else-if="!data.length">
              <td colspan="7" class="text-center" style="padding: 40px; color: #64748b;">
                Belum ada program penyaluran yang dibuat.
              </td>
            </tr>
            <tr v-for="item in data" :key="item.id">
              <td>
                <div style="font-weight: 700; font-size: 13px;">{{ item.name }}</div>
                <div style="font-size: 11px; color: #64748b;">{{ item.description }}</div>
              </td>
              <td><span class="badge badge-purple">{{ item.bidang || '-' }}</span></td>
              <td><span class="badge badge-green">{{ FUND_LABELS[item.fund_type] || item.fund_type }}</span></td>
              <td>
                <div style="font-size: 12px;">{{ item.pic || '-' }}</div>
                <div style="font-size: 10px; color: #64748b;">{{ item.waktu_kegiatan || '-' }}</div>
              </td>
              <td class="text-right font-bold">{{ formatRp(item.target_amount) }}</td>
              <td class="text-right">
                <div style="color: #059669; font-weight: 700;">{{ formatRp(item.realisasi || 0) }}</div>
                <div style="font-size: 10px; color: #64748b;">
                  {{ item.target_amount > 0 ? Math.min(100, Math.round(((item.realisasi || 0) / item.target_amount) * 100)) : 0 }}% terserap
                </div>
              </td>
              <td class="text-center">
                <div style="display: flex; gap: 4px; justify-content: center;">
                  <button class="btn btn-secondary btn-xs" @click="openModal(item)" title="Edit">
                    <Pencil :size="12" />
                  </button>
                  <button class="btn btn-red btn-xs" @click="handleDelete(item.id, item.name)" title="Hapus">
                    <Trash2 :size="12" />
                  </button>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <!-- Modal Form -->
    <div v-if="isModalOpen" class="modal-overlay" @click="isModalOpen = false">
      <div class="modal" @click.stop>
        <div class="modal-header">
          <h3>{{ editItem ? 'Edit Program' : '+ Tambah Program Baru' }}</h3>
          <button class="btn-close" @click="isModalOpen = false">
            <X :size="16" />
          </button>
        </div>
        <form @submit.prevent="handleSubmit">
          <div class="modal-body">
            <div class="form-group">
              <label class="form-label">Nama Program Penyaluran<span class="required">*</span></label>
              <input type="text" class="form-input" placeholder="Contoh: Beasiswa Santri Yatim" v-model="form.name" required />
            </div>

            <div class="form-grid-2">
              <div class="form-group">
                <label class="form-label">Sumber Dana Utama<span class="required">*</span></label>
                <select class="form-select" v-model="form.fund_type">
                  <option value="zakat">Dana Zakat (1101)</option>
                  <option value="infaq_terikat">Dana Infak Terikat (2101)</option>
                  <option value="infaq_tidak_terikat">Dana Infak Tidak Terikat (2102)</option>
                  <option value="amil">Dana Amil (3301)</option>
                </select>
              </div>
              <div class="form-group">
                <label class="form-label">Target Anggaran (Rp)<span class="required">*</span></label>
                <input type="number" class="form-input" placeholder="Contoh: 50000000" v-model="form.target_amount" required />
              </div>
            </div>

            <div class="form-grid-3">
              <div class="form-group">
                <label class="form-label">Bidang Program</label>
                <select class="form-select" v-model="form.bidang">
                  <option value="Pendidikan">Pendidikan</option>
                  <option value="Kesehatan">Kesehatan</option>
                  <option value="Kemanusiaan">Kemanusiaan</option>
                  <option value="Ekonomi">Ekonomi</option>
                  <option value="Dakwah-Advokasi">Dakwah-Advokasi</option>
                </select>
              </div>
              <div class="form-group">
                <label class="form-label">PIC / Penanggung Jawab</label>
                <input type="text" class="form-input" v-model="form.pic" placeholder="Nama PIC" />
              </div>
              <div class="form-group">
                <label class="form-label">Waktu Pelaksanaan</label>
                <input type="text" class="form-input" v-model="form.waktu_kegiatan" placeholder="Tahunan / Ramadhan" />
              </div>
            </div>

            <div class="form-group">
              <label class="form-label">Uraian / Sasaran Program</label>
              <textarea class="form-textarea" rows="2" v-model="form.description"></textarea>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" @click="isModalOpen = false">Batal</button>
            <button type="submit" class="btn btn-primary">
              <Save :size="14" /> Simpan Program
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import api, { formatRp, FUND_LABELS } from '../lib/api';
import { Plus, Pencil, Trash2, X, Save } from '@lucide/vue';

const data = ref<any[]>([]);
const loading = ref(false);
const isModalOpen = ref(false);
const editItem = ref<any | null>(null);

const form = ref({
  name: '',
  fund_type: 'zakat',
  target_amount: '',
  description: '',
  bidang: 'Pendidikan',
  pic: '',
  waktu_kegiatan: 'Tahunan',
});

const fetchData = async () => {
  loading.value = true;
  try {
    const res = await api.get('/programs');
    data.value = res.data || [];
  } catch (err) {
    console.error(err);
  } finally {
    loading.value = false;
  }
};

const openModal = (item?: any) => {
  if (item) {
    editItem.value = item;
    form.value = { ...item, target_amount: item.target_amount?.toString() };
  } else {
    editItem.value = null;
    form.value = {
      name: '',
      fund_type: 'zakat',
      target_amount: '',
      description: '',
      bidang: 'Pendidikan',
      pic: '',
      waktu_kegiatan: 'Tahunan',
    };
  }
  isModalOpen.value = true;
};

const handleSubmit = async () => {
  try {
    const payload = { ...form.value, target_amount: Number(form.value.target_amount) };
    if (editItem.value) {
      await api.put(`/programs/${editItem.value.id}`, payload);
    } else {
      await api.post('/programs', payload);
    }
    isModalOpen.value = false;
    fetchData();
  } catch (err: any) {
    alert(err.response?.data?.message || 'Gagal menyimpan program.');
  }
};

const handleDelete = async (id: number, name: string) => {
  if (!confirm(`Hapus program "${name}"?`)) return;
  try {
    await api.delete(`/programs/${id}`);
    fetchData();
  } catch (err: any) {
    alert(err.response?.data?.message || 'Gagal menghapus.');
  }
};

onMounted(() => {
  fetchData();
});
</script>

// frontend/src/pages/Programs.tsx
import React, { useState, useEffect } from 'react';
import api, { formatRp, FUND_LABELS } from '../lib/api';
import { PlusCircle, Folder, Edit2, Trash2, X, Target, User, Calendar } from 'lucide-react';

export default function Programs() {
  const [data, setData] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editItem, setEditItem] = useState<any | null>(null);

  const [formData, setFormData] = useState({
    name: '',
    fund_type: 'zakat',
    target_amount: '',
    description: '',
    bidang: 'Pendidikan',
    pic: '',
    waktu_kegiatan: 'Tahunan',
  });

  const fetchData = async () => {
    setLoading(true);
    try {
      const res = await api.get('/programs');
      setData(res.data || []);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  const handleOpenModal = (item?: any) => {
    if (item) {
      setEditItem(item);
      setFormData({
        name: item.name || '',
        fund_type: item.fund_type || 'zakat',
        target_amount: item.target_amount?.toString() || '',
        description: item.description || '',
        bidang: item.bidang || 'Pendidikan',
        pic: item.pic || '',
        waktu_kegiatan: item.waktu_kegiatan || 'Tahunan',
      });
    } else {
      setEditItem(null);
      setFormData({
        name: '',
        fund_type: 'zakat',
        target_amount: '',
        description: '',
        bidang: 'Pendidikan',
        pic: '',
        waktu_kegiatan: 'Tahunan',
      });
    }
    setIsModalOpen(true);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      const payload = { ...formData, target_amount: Number(formData.target_amount) };
      if (editItem) {
        await api.put(`/programs/${editItem.id}`, payload);
      } else {
        await api.post('/programs', payload);
      }
      setIsModalOpen(false);
      fetchData();
    } catch (err: any) {
      alert(err.response?.data?.message || 'Gagal menyimpan program.');
    }
  };

  const handleDelete = async (id: number, name: string) => {
    if (!confirm(`Hapus program "${name}"?`)) return;
    try {
      await api.delete(`/programs/${id}`);
      fetchData();
    } catch (err: any) {
      alert(err.response?.data?.message || 'Gagal menghapus program.');
    }
  };

  return (
    <div>
      <div className="section-header">
        <div>
          <h3>Program Penyaluran ZIS</h3>
          <p>Daftar alokasi program kerja penyaluran UPZ Kemenag</p>
        </div>
        <button className="btn btn-primary" onClick={() => handleOpenModal()}>
          <PlusCircle size={14} /> + Tambah Program
        </button>
      </div>

      <div className="card">
        <div className="table-container">
          <table>
            <thead>
              <tr>
                <th>NAMA PROGRAM</th>
                <th>BIDANG</th>
                <th>SUMBER DANA</th>
                <th>PIC / WAKTU</th>
                <th className="text-right">TARGET ANGGARAN</th>
                <th className="text-right">REALISASI</th>
                <th className="text-center">AKSI</th>
              </tr>
            </thead>
            <tbody>
              {loading && data.length === 0 ? (
                <tr>
                  <td colSpan={7} className="text-center" style={{ padding: '30px' }}>
                    <span className="loading-spinner" style={{ width: 18, height: 18, marginRight: 8 }} />
                    Memuat data...
                  </td>
                </tr>
              ) : data.length === 0 ? (
                <tr>
                  <td colSpan={7} className="text-center" style={{ padding: '40px', color: 'var(--text-muted)' }}>
                    Belum ada program penyaluran yang dibuat.
                  </td>
                </tr>
              ) : (
                data.map(item => {
                  const target = Number(item.target_amount) || 0;
                  const real = Number(item.realisasi) || 0;
                  const pct = target > 0 ? Math.min(100, Math.round((real / target) * 100)) : 0;
                  return (
                    <tr key={item.id}>
                      <td>
                        <div style={{ fontWeight: 600, fontSize: '13px' }}>{item.name}</div>
                        <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>{item.description}</div>
                      </td>
                      <td><span className="badge badge-purple">{item.bidang || '-'}</span></td>
                      <td><span className="badge badge-green">{FUND_LABELS[item.fund_type] || item.fund_type}</span></td>
                      <td>
                        <div style={{ fontSize: '12px' }}>{item.pic || '-'}</div>
                        <div style={{ fontSize: '10px', color: 'var(--text-muted)' }}>{item.waktu_kegiatan || '-'}</div>
                      </td>
                      <td className="text-right font-bold">{formatRp(target)}</td>
                      <td className="text-right">
                        <div style={{ color: 'var(--accent-green)', fontWeight: 600 }}>{formatRp(real)}</div>
                        <div style={{ fontSize: '10px', color: 'var(--text-muted)' }}>{pct}% terserap</div>
                      </td>
                      <td className="text-center">
                        <div style={{ display: 'flex', gap: '4px', justifyContent: 'center' }}>
                          <button className="btn btn-secondary btn-xs" onClick={() => handleOpenModal(item)}>
                            <Edit2 size={12} />
                          </button>
                          <button className="btn btn-red btn-xs" onClick={() => handleDelete(item.id, item.name)}>
                            <Trash2 size={12} />
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      </div>

      {isModalOpen && (
        <div className="modal-overlay" onClick={() => setIsModalOpen(false)}>
          <div className="modal" onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <h3>{editItem ? 'Edit Program' : '+ Tambah Program Baru'}</h3>
              <button className="btn-close" onClick={() => setIsModalOpen(false)}><X size={16} /></button>
            </div>
            <form onSubmit={handleSubmit}>
              <div className="modal-body">
                <div className="form-group">
                  <label className="form-label">Nama Program Penyaluran<span className="required">*</span></label>
                  <input
                    type="text"
                    className="form-input"
                    value={formData.name}
                    onChange={e => setFormData({ ...formData, name: e.target.value })}
                    placeholder="Contoh: Beasiswa Santri & Yatim Dhuafa"
                    required
                  />
                </div>

                <div className="form-grid-2">
                  <div className="form-group">
                    <label className="form-label">Sumber Dana Utama<span className="required">*</span></label>
                    <select
                      className="form-select"
                      value={formData.fund_type}
                      onChange={e => setFormData({ ...formData, fund_type: e.target.value })}
                    >
                      <option value="zakat">Dana Zakat (1101)</option>
                      <option value="infaq_terikat">Dana Infak Terikat (2101)</option>
                      <option value="infaq_tidak_terikat">Dana Infak Tidak Terikat (2102)</option>
                      <option value="amil">Dana Amil (3301)</option>
                    </select>
                  </div>
                  <div className="form-group">
                    <label className="form-label">Target Anggaran (Rp)<span className="required">*</span></label>
                    <input
                      type="number"
                      className="form-input"
                      value={formData.target_amount}
                      onChange={e => setFormData({ ...formData, target_amount: e.target.value })}
                      placeholder="Contoh: 50000000"
                      required
                    />
                  </div>
                </div>

                <div className="form-grid-3">
                  <div className="form-group">
                    <label className="form-label">Bidang Program</label>
                    <select
                      className="form-select"
                      value={formData.bidang}
                      onChange={e => setFormData({ ...formData, bidang: e.target.value })}
                    >
                      <option value="Pendidikan">Pendidikan</option>
                      <option value="Kesehatan">Kesehatan</option>
                      <option value="Kemanusiaan">Kemanusiaan</option>
                      <option value="Ekonomi">Ekonomi</option>
                      <option value="Dakwah-Advokasi">Dakwah-Advokasi</option>
                    </select>
                  </div>
                  <div className="form-group">
                    <label className="form-label">Penanggung Jawab (PIC)</label>
                    <input
                      type="text"
                      className="form-input"
                      value={formData.pic}
                      onChange={e => setFormData({ ...formData, pic: e.target.value })}
                      placeholder="Nama PIC"
                    />
                  </div>
                  <div className="form-group">
                    <label className="form-label">Waktu Pelaksanaan</label>
                    <input
                      type="text"
                      className="form-input"
                      value={formData.waktu_kegiatan}
                      onChange={e => setFormData({ ...formData, waktu_kegiatan: e.target.value })}
                      placeholder="Tahunan / Ramadhan"
                    />
                  </div>
                </div>

                <div className="form-group">
                  <label className="form-label">Uraian / Sasaran Program</label>
                  <textarea
                    className="form-textarea"
                    rows={2}
                    value={formData.description}
                    onChange={e => setFormData({ ...formData, description: e.target.value })}
                  />
                </div>
              </div>
              <div className="modal-footer">
                <button type="button" className="btn btn-secondary" onClick={() => setIsModalOpen(false)}>Batal</button>
                <button type="submit" className="btn btn-primary">Simpan Program</button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
