// frontend-vue/src/views/Settings.vue
<template>
  <div>
    <div class="section-header">
      <div>
        <h3>Pengaturan Sistem & Parameter UPZ</h3>
        <p>Konfigurasi identitas organisasi, rekening kas/bank, dan parameter zakat</p>
      </div>
    </div>

    <div class="page-grid-2">
      <!-- Identitas UPZ -->
      <div class="card">
        <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 16px;">
          <Building2 :size="18" color="#059669" />
          <h4 style="font-size: 15px; font-weight: 700;">Identitas Instansi & Sistem</h4>
        </div>
        <form @submit.prevent="saveSettings">
          <div class="form-group">
            <label class="form-label">Nama UPZ</label>
            <input type="text" class="form-input" v-model="settings.upz_name" />
          </div>
          <div class="form-group">
            <label class="form-label">Alamat Kantor</label>
            <textarea class="form-textarea" rows="2" v-model="settings.upz_address"></textarea>
          </div>
          <div class="form-grid-2">
            <div class="form-group">
              <label class="form-label">Nomor Telepon</label>
              <input type="text" class="form-input" v-model="settings.upz_phone" />
            </div>
            <div class="form-group">
              <label class="form-label">Nama BAZNAS Induk</label>
              <input type="text" class="form-input" v-model="settings.baznas_name" />
            </div>
          </div>
          <div class="form-grid-2">
            <div class="form-group">
              <label class="form-label">Tahun Buku Aktif</label>
              <input type="text" class="form-input" v-model="settings.fiscal_year" />
            </div>
            <div class="form-group">
              <label class="form-label">Batas Hak Amil Max (%)</label>
              <input type="number" step="0.1" class="form-input" v-model="settings.amil_max_percentage" />
            </div>
          </div>

          <button type="submit" class="btn btn-primary" style="margin-top: 12px;" :disabled="saving">
            <Save :size="14" /> {{ saving ? 'Menyimpan...' : 'Simpan Pengaturan' }}
          </button>
        </form>
      </div>

      <!-- Rekening Bank -->
      <div class="card">
        <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 16px;">
          <CreditCard :size="18" color="#2563eb" />
          <h4 style="font-size: 15px; font-weight: 700;">Daftar Rekening Bank Aktif</h4>
        </div>

        <div style="margin-bottom: 20px; display: flex; flex-direction: column; gap: 8px;">
          <div
            v-for="b in bankAccounts"
            :key="b.id"
            style="background: #f8fafc; border: 1px solid var(--border); border-radius: var(--radius-sm); padding: 10px 14px; display: flex; align-items: center; justify-content: space-between;"
          >
            <div>
              <div style="font-weight: 700; font-size: 13px;">{{ b.bank_name }} - {{ b.account_number }}</div>
              <div style="font-size: 11px; color: #64748b;">
                a.n. {{ b.account_holder }} •
                <span class="badge badge-gray" style="font-size: 9px; margin-left: 4px; text-transform: uppercase;">{{ b.type }}</span>
                <span v-if="b.fund_type" class="badge badge-green" style="font-size: 9px; margin-left: 4px;">
                  Pos {{ b.fund_type?.replace(/_/g, ' ').toUpperCase() }}
                </span>
              </div>
            </div>
            <button class="btn btn-red btn-xs" @click="handleDeleteBank(b.id)" title="Hapus">
              <Trash2 :size="12" />
            </button>
          </div>
        </div>

        <form @submit.prevent="handleAddBank" style="border-top: 1px solid var(--border); padding-top: 16px;">
          <div style="font-size: 12px; font-weight: 700; color: #334155; margin-bottom: 8px;">
            + Tambah Rekening Bank Pos
          </div>
          <div class="form-grid-2">
            <div class="form-group">
              <label class="form-label" style="font-size: 11px;">Nama Bank</label>
              <input type="text" class="form-input" placeholder="Contoh: BSI / Bank Jateng" v-model="newBank.bank_name" required />
            </div>
            <div class="form-group">
              <label class="form-label" style="font-size: 11px;">Nomor Rekening</label>
              <input type="text" class="form-input" placeholder="Nomor Rekening" v-model="newBank.account_number" required />
            </div>
          </div>
          <div class="form-grid-3">
            <div class="form-group">
              <label class="form-label" style="font-size: 11px;">Nama Pemilik</label>
              <input type="text" class="form-input" placeholder="Nama Pemilik Rekening" v-model="newBank.account_holder" required />
            </div>
            <div class="form-group">
              <label class="form-label" style="font-size: 11px;">Tipe Rekening</label>
              <select class="form-select" v-model="newBank.type">
                <option value="upz">Rekening UPZ Kemenag</option>
                <option value="baznas">Rekening BAZNAS Kebumen</option>
                <option value="upz_penghimpunan">Rekening Penampungan ZIS</option>
              </select>
            </div>
            <div class="form-group">
              <label class="form-label" style="font-size: 11px;">Peruntukan Pos Dana</label>
              <select class="form-select" v-model="newBank.fund_type">
                <option value="">Umum / Bebas</option>
                <option value="zakat">Pos Dana Zakat (1101)</option>
                <option value="infaq_terikat">Pos Dana Infak Terikat (2101)</option>
                <option value="infaq_tidak_terikat">Pos Dana Infak Bebas (2102)</option>
                <option value="amil">Pos Hak Amil (3301)</option>
                <option value="non_halal">Pos Non Halal (3401)</option>
              </select>
            </div>
          </div>
          <button type="submit" class="btn btn-secondary btn-sm">
            <Plus :size="13" /> Tambah Rekening Pos
          </button>
        </form>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import api from '../lib/api';
import { Building2, CreditCard, Save, Trash2, Plus } from '@lucide/vue';

const settings = ref<Record<string, any>>({
  upz_name: 'UPZ P Kankemenag Kab. Kebumen',
  upz_address: 'Jl. Pahlawan No. 123, Kebumen, Jawa Tengah',
  upz_phone: '(0287) 381101',
  baznas_name: 'BAZNAS Kabupaten Kebumen',
  fiscal_year: '2026',
  amil_max_percentage: '12.5',
});
const bankAccounts = ref<any[]>([]);
const saving = ref(false);

const newBank = ref({
  type: 'upz',
  fund_type: '',
  bank_name: '',
  account_number: '',
  account_holder: '',
  description: '',
});

const fetchData = async () => {
  try {
    const [resSet, resBank] = await Promise.all([
      api.get('/settings'),
      api.get('/bank-accounts'),
    ]);
    const setMap: Record<string, string> = {};
    Object.keys(resSet.data || {}).forEach(k => {
      setMap[k] = resSet.data[k]?.value || '';
    });
    settings.value = { ...settings.value, ...setMap };
    bankAccounts.value = resBank.data || [];
  } catch (err) {
    console.error(err);
  }
};

const saveSettings = async () => {
  saving.value = true;
  try {
    await api.post('/settings', settings.value);
    alert('Pengaturan sistem berhasil disimpan!');
  } catch (err: any) {
    alert(err.response?.data?.message || 'Gagal.');
  } finally {
    saving.value = false;
  }
};

const handleAddBank = async () => {
  try {
    await api.post('/bank-accounts', newBank.value);
    newBank.value = { type: 'upz', fund_type: '', bank_name: '', account_number: '', account_holder: '', description: '' };
    const res = await api.get('/bank-accounts');
    bankAccounts.value = res.data || [];
    alert('Rekening bank pos berhasil ditambahkan!');
  } catch (err: any) {
    alert(err.response?.data?.message || 'Gagal.');
  }
};

const handleDeleteBank = async (id: number) => {
  if (!confirm('Hapus rekening bank ini?')) return;
  try {
    await api.delete(`/bank-accounts/${id}`);
    bankAccounts.value = bankAccounts.value.filter(b => b.id !== id);
  } catch (err: any) {
    alert(err.response?.data?.message || 'Gagal.');
  }
};

onMounted(() => {
  fetchData();
});
</script>

// frontend/src/pages/Settings.tsx
import React, { useState, useEffect } from 'react';
import api from '../lib/api';
import { Settings as SettingsIcon, Save, Building, CreditCard, PlusCircle, Trash2 } from 'lucide-react';

export default function Settings() {
  const [settings, setSettings] = useState<Record<string, any>>({});
  const [bankAccounts, setBankAccounts] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);

  // New Bank Account Form State
  const [newBank, setNewBank] = useState({
    type: 'upz',
    bank_name: '',
    account_number: '',
    account_holder: '',
    description: '',
  });

  const fetchData = async () => {
    setLoading(true);
    try {
      const [resSet, resBank] = await Promise.all([
        api.get('/settings'),
        api.get('/bank-accounts'),
      ]);
      const setMap: Record<string, string> = {};
      Object.keys(resSet.data || {}).forEach(k => {
        setMap[k] = resSet.data[k]?.value || '';
      });
      setSettings(setMap);
      setBankAccounts(resBank.data || []);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  const handleSaveSettings = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaving(true);
    try {
      await api.post('/settings', settings);
      alert('Pengaturan sistem berhasil disimpan!');
    } catch (err: any) {
      alert(err.response?.data?.message || 'Gagal menyimpan pengaturan.');
    } finally {
      setSaving(false);
    }
  };

  const handleAddBank = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newBank.bank_name || !newBank.account_number || !newBank.account_holder) {
      alert('Lengkapi data rekening bank.');
      return;
    }
    try {
      await api.post('/bank-accounts', newBank);
      setNewBank({ type: 'upz', bank_name: '', account_number: '', account_holder: '', description: '' });
      const res = await api.get('/bank-accounts');
      setBankAccounts(res.data || []);
      alert('Rekening bank berhasil ditambahkan!');
    } catch (err: any) {
      alert(err.response?.data?.message || 'Gagal menambah rekening.');
    }
  };

  const handleDeleteBank = async (id: number) => {
    if (!confirm('Hapus rekening bank ini?')) return;
    try {
      await api.delete(`/bank-accounts/${id}`);
      setBankAccounts(prev => prev.filter(b => b.id !== id));
    } catch (err: any) {
      alert(err.response?.data?.message || 'Gagal menghapus rekening.');
    }
  };

  return (
    <div>
      <div className="section-header">
        <div>
          <h3>Pengaturan Sistem & Parameter UPZ</h3>
          <p>Konfigurasi identitas organisasi, rekening kas/bank, dan parameter zakat</p>
        </div>
      </div>

      <div className="page-grid-2">
        {/* Identitas UPZ */}
        <div className="card">
          <h4 style={{ fontSize: '15px', fontWeight: 700, marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <Building size={16} color="var(--accent-green)" /> Identitas Instansi & Sistem
          </h4>
          <form onSubmit={handleSaveSettings}>
            <div className="form-group">
              <label className="form-label">Nama UPZ</label>
              <input
                type="text"
                className="form-input"
                value={settings.upz_name || ''}
                onChange={e => setSettings({ ...settings, upz_name: e.target.value })}
              />
            </div>
            <div className="form-group">
              <label className="form-label">Alamat Kantor</label>
              <textarea
                className="form-textarea"
                rows={2}
                value={settings.upz_address || ''}
                onChange={e => setSettings({ ...settings, upz_address: e.target.value })}
              />
            </div>
            <div className="form-grid-2">
              <div className="form-group">
                <label className="form-label">Nomor Telepon</label>
                <input
                  type="text"
                  className="form-input"
                  value={settings.upz_phone || ''}
                  onChange={e => setSettings({ ...settings, upz_phone: e.target.value })}
                />
              </div>
              <div className="form-group">
                <label className="form-label">Nama BAZNAS Induk</label>
                <input
                  type="text"
                  className="form-input"
                  value={settings.baznas_name || ''}
                  onChange={e => setSettings({ ...settings, baznas_name: e.target.value })}
                />
              </div>
            </div>
            <div className="form-grid-2">
              <div className="form-group">
                <label className="form-label">Tahun Buku Aktif</label>
                <input
                  type="text"
                  className="form-input"
                  value={settings.fiscal_year || '2026'}
                  onChange={e => setSettings({ ...settings, fiscal_year: e.target.value })}
                />
              </div>
              <div className="form-group">
                <label className="form-label">Batas Hak Amil Max (%)</label>
                <input
                  type="number"
                  step="0.1"
                  className="form-input"
                  value={settings.amil_max_percentage || '12.5'}
                  onChange={e => setSettings({ ...settings, amil_max_percentage: e.target.value })}
                />
              </div>
            </div>

            <button type="submit" className="btn btn-primary" style={{ marginTop: '12px' }} disabled={saving}>
              <Save size={14} /> {saving ? 'Menyimpan...' : 'Simpan Pengaturan'}
            </button>
          </form>
        </div>

        {/* Rekening Bank */}
        <div className="card">
          <h4 style={{ fontSize: '15px', fontWeight: 700, marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <CreditCard size={16} color="var(--accent-blue)" /> Daftar Rekening Bank Aktif
          </h4>

          {/* List Existing Bank Accounts */}
          <div style={{ marginBottom: '20px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
            {bankAccounts.map(b => (
              <div
                key={b.id}
                style={{
                  background: 'rgba(255,255,255,0.03)',
                  border: '1px solid var(--border)',
                  borderRadius: 'var(--radius-sm)',
                  padding: '10px 14px',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                }}
              >
                <div>
                  <div style={{ fontWeight: 600, fontSize: '13px' }}>{b.bank_name} - {b.account_number}</div>
                  <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>
                    a.n. {b.account_holder} • <span style={{ textTransform: 'uppercase' }}>{b.type}</span>
                  </div>
                </div>
                <button className="btn btn-red btn-xs" onClick={() => handleDeleteBank(b.id)}>
                  <Trash2 size={12} />
                </button>
              </div>
            ))}
          </div>

          {/* Add Bank Form */}
          <form onSubmit={handleAddBank} style={{ borderTop: '1px solid var(--border)', paddingTop: '16px' }}>
            <div style={{ fontSize: '12px', fontWeight: 600, color: 'var(--text-secondary)', marginBottom: '8px' }}>
              + Tambah Rekening Bank
            </div>
            <div className="form-grid-2">
              <div className="form-group">
                <input
                  type="text"
                  className="form-input"
                  placeholder="Nama Bank (cth: BSI / Bank Jateng)"
                  value={newBank.bank_name}
                  onChange={e => setNewBank({ ...newBank, bank_name: e.target.value })}
                  required
                />
              </div>
              <div className="form-group">
                <input
                  type="text"
                  className="form-input"
                  placeholder="Nomor Rekening"
                  value={newBank.account_number}
                  onChange={e => setNewBank({ ...newBank, account_number: e.target.value })}
                  required
                />
              </div>
            </div>
            <div className="form-grid-2">
              <div className="form-group">
                <input
                  type="text"
                  className="form-input"
                  placeholder="Nama Pemilik Rekening"
                  value={newBank.account_holder}
                  onChange={e => setNewBank({ ...newBank, account_holder: e.target.value })}
                  required
                />
              </div>
              <div className="form-group">
                <select
                  className="form-select"
                  value={newBank.type}
                  onChange={e => setNewBank({ ...newBank, type: e.target.value })}
                >
                  <option value="upz">Rekening UPZ Kemenag</option>
                  <option value="baznas">Rekening BAZNAS Kebumen</option>
                  <option value="upz_penghimpunan">Rekening Khusus Penghimpunan</option>
                </select>
              </div>
            </div>
            <button type="submit" className="btn btn-secondary btn-sm">
              <PlusCircle size={13} /> Tambah Rekening
            </button>
          </form>
        </div>
      </div>
    </div>
  );
}
