// frontend-vue/src/App.vue
<template>
  <div v-if="!currentUser">
    <Login @login-success="handleLoginSuccess" />
  </div>
  <div v-else>
    <Layout :active-tab="activeTab" :user="currentUser" @navigate="activeTab = $event" @logout="handleLogout">
      <!-- 1. Dashboard -->
      <Dashboard v-if="activeTab === 'dashboard'" @navigate="activeTab = $event" />

      <!-- 2. Master Data -->
      <Muzakki v-else-if="activeTab === 'muzakki'" />
      <Mustahik v-else-if="activeTab === 'mustahik'" />

      <!-- 3. Perencanaan -->
      <CollectionPlans v-else-if="activeTab === 'collection-plans'" />
      <Programs v-else-if="activeTab === 'programs'" />
      <ProgramControl v-else-if="activeTab === 'program-control'" />

      <!-- 4. Transaksi -->
      <Transactions
        v-else-if="['penerimaan', 'penyaluran', 'operasional'].includes(activeTab)"
        :transaction-type="activeTab === 'operasional' ? 'amil_operasional' : (activeTab as any)"
        :user="currentUser"
      />

      <!-- 5. Pembukuan & Laporan PSAK 109 -->
      <Reports
        v-else-if="[
          'posisi-keuangan', 'perubahan-dana', 'arus-kas',
          'buku-kas', 'buku-besar', 'neraca-saldo', 'mutasi-kas-bank', 'jurnal-umum'
        ].includes(activeTab)"
        :report-type="activeTab"
      />

      <!-- 6. Bagan Akun -->
      <ChartOfAccounts v-else-if="activeTab === 'chart-of-accounts'" />

      <!-- 7. Regulator & Arsip -->
      <BaznasKebumen v-else-if="activeTab === 'baznas'" />
      <DigitalArchive v-else-if="activeTab === 'arsip-digital'" />

      <!-- 8. Sistem & Alat -->
      <KalkulatorZakat v-else-if="activeTab === 'kalkulator-zakat'" />
      <BackupRestore v-else-if="activeTab === 'backup-restore'" />
      <AuditLog v-else-if="activeTab === 'audit-log'" :user="currentUser" />
      <Users v-else-if="activeTab === 'users'" />
      <Settings v-else-if="activeTab === 'settings'" />
    </Layout>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import Layout from './components/Layout.vue';
import Login from './views/Login.vue';
import Dashboard from './views/Dashboard.vue';
import Muzakki from './views/Muzakki.vue';
import Mustahik from './views/Mustahik.vue';
import Transactions from './views/Transactions.vue';
import Programs from './views/Programs.vue';
import ProgramControl from './views/ProgramControl.vue';
import CollectionPlans from './views/CollectionPlans.vue';
import Reports from './views/Reports.vue';
import BaznasKebumen from './views/BaznasKebumen.vue';
import DigitalArchive from './views/DigitalArchive.vue';
import KalkulatorZakat from './views/KalkulatorZakat.vue';
import AuditLog from './views/AuditLog.vue';
import Users from './views/Users.vue';
import Settings from './views/Settings.vue';
import BackupRestore from './views/BackupRestore.vue';
import ChartOfAccounts from './views/ChartOfAccounts.vue';

const activeTab = ref('dashboard');
const currentUser = ref<any | null>(null);

onMounted(() => {
  const token = localStorage.getItem('token');
  const userJson = localStorage.getItem('user');
  if (token && userJson) {
    try {
      currentUser.value = JSON.parse(userJson);
    } catch {
      currentUser.value = null;
    }
  }
});

const handleLoginSuccess = (user: any) => {
  currentUser.value = user;
  activeTab.value = 'dashboard';
};

const handleLogout = () => {
  localStorage.removeItem('token');
  localStorage.removeItem('user');
  currentUser.value = null;
};
</script>

// frontend/src/App.tsx
import React, { useState } from 'react';
import { AuthProvider, useAuth } from './context/AuthContext';
import Layout from './components/Layout';
import Login from './pages/Login';
import Dashboard from './pages/Dashboard';
import Muzakki from './pages/Muzakki';
import Mustahik from './pages/Mustahik';
import Transactions from './pages/Transactions';
import Programs from './pages/Programs';
import CollectionPlans from './pages/CollectionPlans';
import ProgramControl from './pages/ProgramControl';
import BaznasKebumen from './pages/BaznasKebumen';
import DigitalArchive from './pages/DigitalArchive';
import KalkulatorZakat from './pages/KalkulatorZakat';
import AuditLog from './pages/AuditLog';
import Settings from './pages/Settings';
import Users from './pages/Users';
import BackupRestore from './pages/BackupRestore';
import LimitMonitor from './pages/LimitMonitor';
import ChartOfAccounts from './pages/ChartOfAccounts';
import {
  PosisiKeuangan, PerubahanDana, ArusKas,
  BukuKas, BukuBesar, NeracaSaldo, MutasiKasBank, JurnalUmum
} from './pages/Reports';

function AppContent() {
  const { user } = useAuth();
  const [activePage, setActivePage] = useState('dashboard');

  if (!user) return <Login />;

  const renderPage = () => {
    switch (activePage) {
      case 'dashboard':      return <Dashboard onNavigate={setActivePage} />;
      case 'muzakki':        return <Muzakki />;
      case 'mustahik':       return <Mustahik />;
      case 'penerimaan':     return <Transactions transactionType="penerimaan" />;
      case 'penyaluran':     return <Transactions transactionType="penyaluran" />;
      case 'operasional':    return <Transactions transactionType="amil_operasional" />;
      case 'programs':       return <Programs />;
      case 'collection-plans': return <CollectionPlans />;
      case 'program-control':  return <ProgramControl />;
      case 'baznas':         return <BaznasKebumen />;
      case 'arsip-digital':  return <DigitalArchive />;
      case 'kalkulator-zakat': return <KalkulatorZakat />;
      case 'audit-log':      return <AuditLog />;
      case 'settings':       return <Settings />;
      case 'users':          return <Users />;
      case 'backup-restore': return <BackupRestore />;
      case 'limit-monitor':  return <LimitMonitor />;
      case 'chart-of-accounts': return <ChartOfAccounts />;
      // Pembukuan
      case 'buku-kas':       return <BukuKas />;
      case 'buku-besar':     return <BukuBesar />;
      case 'neraca-saldo':   return <NeracaSaldo />;
      case 'mutasi-kas-bank':return <MutasiKasBank />;
      case 'jurnal-umum':    return <JurnalUmum />;
      // Laporan PSAK 109
      case 'posisi-keuangan':  return <PosisiKeuangan />;
      case 'perubahan-dana':   return <PerubahanDana />;
      case 'arus-kas':         return <ArusKas />;
      default: return <Dashboard onNavigate={setActivePage} />;
    }
  };

  const PAGE_TITLES: Record<string, string> = {
    dashboard: 'Ikhtisar Dashboard Utama',
    muzakki: 'Data Muzakki / Donatur',
    mustahik: 'Data Mustahik (Penerima 8 Asnaf)',
    penerimaan: 'Penerimaan Dana ZIS',
    penyaluran: 'Penyaluran Dana ZIS',
    operasional: 'Pengeluaran Operasional Amil',
    programs: 'Program Penyaluran ZIS',
    'collection-plans': 'Rencana Penghimpunan ZIS',
    'program-control': 'Kontrol & Monitor Program',
    baznas: 'Setoran & Laporan BAZNAS Kebumen',
    'arsip-digital': 'Arsip Digital & Bukti Transaksi',
    'kalkulator-zakat': 'Kalkulator Zakat',
    'audit-log': 'Log Aktivitas User (Audit Trail)',
    settings: 'Pengaturan Sistem',
    users: 'Manajemen Pengguna',
    'backup-restore': 'Backup & Restore Data',
    'limit-monitor': 'Monitor Limit & Kuota Sistem',
    'chart-of-accounts': 'Bagan Akun (Chart of Accounts)',
    'buku-kas': 'Buku Kas Umum',
    'buku-besar': 'Buku Besar (General Ledger)',
    'neraca-saldo': 'Neraca Saldo (Trial Balance)',
    'mutasi-kas-bank': 'Mutasi Kas & Bank',
    'jurnal-umum': 'Jurnal Umum',
    'posisi-keuangan': 'Laporan Posisi Keuangan — PSAK 109',
    'perubahan-dana': 'Laporan Perubahan Dana — PSAK 109',
    'arus-kas': 'Laporan Arus Kas — PSAK 109',
  };

  return (
    <Layout activePage={activePage} onNavigate={setActivePage} pageTitle={PAGE_TITLES[activePage]}>
      {renderPage()}
    </Layout>
  );
}

export default function App() {
  return (
    <AuthProvider>
      <AppContent />
    </AuthProvider>
  );
}
